language: ruby

rvm:
  - 2.6.3

cache:
  bundler: true
bundler_args: --without development production
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=test
- bundle exec rake admin:categories:create
